### ISSUE TITLE
'Undefined is not a function' in ctrl-dir-scroll.coffee:20

### ISSUE THREAD

**Issue by trkoch** [callum-ramage/ctrl-dir-scroll#3]
ctrl-dir-scroll stopped working in Atom 0.136.0.
